# List of plugins
set -g prefix C-Space
set -g prefix2 C-b
bind C-Space send-prefix

bind q source-file ~/.config/tmux/tmux.conf

setw -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel

bind-key h select-pane -L
bind-key l select-pane -R
bind-key k select-pane -U
bind-key j select-pane -D

# Session controls
bind R command-prompt -I "#S" "rename-session -- '%%'"
bind C new-session -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
bind K kill-session
bind P switch-client -p
bind N switch-client -n
bind -n M-Up switch-client -p
bind -n M-Down switch-client -n
bind k kill-window

# General
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",*:RGB"
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g history-limit 50000
set -g escape-time 0
set -g focus-events on
set -g set-clipboard on
set -g allow-passthrough on
setw -g aggressive-resize on
set -g detach-on-destroy off
set -g extended-keys on
set -g extended-keys-format csi-u
set -sg escape-time 10

selectedColor="#88C0D0"

# Status bar
set-option -g status-position top
set -g status-left-length 100
set -g status-style bg=default

set -g status-left ""
set -g status-right ""
set -g window-status-current-format "#[fg=${selectedColor}, bold] #I:#W "
set -g window-status-format "  #I:#W "
set -g pane-active-border-style "fg=default"

