-- Generated by nwg-displays on 2026-05-24 at 21:48:01. Do not edit manually.
hl.monitor({
	output = "DP-2",
	mode = "1920x1080@240.0",
	position = "0x0",
	scale = 1.0,
})
hl.monitor({
	output = "DP-3",
	mode = "2560x1440@180.00",
	position = "1920x0",
	scale = 1.0,
})
